import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../UI/Header"
import Layout from "@/UI/Layout";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import 'react-slideshow-image/dist/styles.css'
import Foter from "@/UI/Foter";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Layout>
        <Header></Header>
        {children}
        <Foter/>
      </Layout>
      </body>
    </html>
  );
}
